#IPMC CONFIG

[I2C_ADAPTERS]
i2c_cadence = 7					#i2c cadence adapter number for IPMC-Shelf Manager exchange
i2c_xilinx = 5					#i2c xilinx adapter number for IPMC-Shelf Manager exchange

[I2C_SENSORS]
i2c_sensor = [4,1,2]			#i2c sensor adapter number array (for sensor reading)

[PAYLOAD_M]
man_payload_status = 0			#enable/disable MANUAL management: 1 = ON, 0 = OFF.
man_payload = 0					#payload: 1 = ON, 0 = OFF.

[HANDLE_SWITCH_M]
man_handle_status = 1			#enable/disable MANUAL management: 1 = ON, 0 = OFF.
man_handle_switch = 1			#handle switch: 0 = CLOSED, 1 = OPENED.

[POWER_DRAW]
desired_steady_state = 0xbe		#desired power draw  = 200 Watts (190 W + 10 W already allocated by the Shelf Manager)





