set_false_path -to [get_pins [list bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_rx_done_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_tx_done_inst/rst_in_meta_reg/D \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_meta_reg/D \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_meta_reg/D} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_meta_reg/D} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_meta_reg/D} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_meta_reg/D} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_meta_reg/D} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_meta_reg/D} \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_rx_done_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_tx_done_inst/rst_in_meta_reg/D \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_meta_reg/D]] -quiet
set_false_path -to [get_pins [list bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_meta_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_meta_reg/PRE \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_meta_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_meta_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_meta_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_meta_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_meta_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_meta_reg/PRE} \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_meta_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_meta_reg/PRE]] -quiet
set_false_path -to [get_pins [list bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync1_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync1_reg/PRE \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync1_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync1_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync1_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync1_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync1_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync1_reg/PRE} \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync1_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync1_reg/PRE]] -quiet
set_false_path -to [get_pins [list bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync2_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync2_reg/PRE \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync2_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync2_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync2_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync2_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync2_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync2_reg/PRE} \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync2_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync2_reg/PRE]] -quiet
set_false_path -to [get_pins [list bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync3_reg/PRE \
          bdw/design_1_i/XG_0/xxv_ethernet_0/inst/i_XG_inst_0_xxv_ethernet_0_0_gt/inst/gen_gtwizard_gthe4_top.XG_inst_0_xxv_ethernet_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync3_reg/PRE \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync3_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync3_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync3_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync3_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync3_reg/PRE} \
          {c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_cpll_cal_gthe4.gen_cpll_cal_inst[1].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gthe4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync3_reg/PRE} \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync3_reg/PRE \
          c2c_mgt/example_wrapper_inst/c2c_gth_7p8125g_inst/inst/gen_gtwizard_gthe4_top.c2c_gth_7p8125g_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync3_reg/PRE]] -quiet
create_clock -period 6.400 -name gth_refclk1_c2m_p [get_ports som240_2_a7]
create_clock -period 6.400 -name gth_refclk0_c2m_p [get_ports som240_2_c3]

# False path constraints
# ----------------------------------------------------------------------------------------------------------------------
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *bit_synchronizer*inst/i_in_meta_reg}]
##set_false_path -to [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_*_reg}] -quiet
set_false_path -to [get_pins -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_meta*}]]
set_false_path -to [get_pins -filter REF_PIN_NAME=~*PRE -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_meta*}]]
set_false_path -to [get_pins -filter REF_PIN_NAME=~*PRE -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_sync1*}]]
set_false_path -to [get_pins -filter REF_PIN_NAME=~*PRE -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_sync2*}]]
set_false_path -to [get_pins -filter REF_PIN_NAME=~*PRE -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_sync3*}]]
set_false_path -to [get_pins -filter REF_PIN_NAME=~*PRE -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_out*}]]


set_false_path -to [get_cells -hierarchical -filter {NAME =~ *gtwiz_userclk_tx_inst/*gtwiz_userclk_tx_active_*_reg}]
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *gtwiz_userclk_rx_inst/*gtwiz_userclk_rx_active_*_reg}]

